source "https://api.berkshelf.com"

cookbook 'yum-pkg', path: 'yum-pkg'
cookbook "rails_book_cookbook", path: "./site-cookbooks/rails_book_cookbook"

cookbook 'git'
cookbook 'build-essential'
cookbook 'vim'
cookbook 'openssl'
#cookbook 'memcached'
cookbook 'nodejs'
#cookbook 'database'
cookbook 'xml'
cookbook 'ruby_build'
cookbook 'rbenv', :git => 'git://github.com/fnichol/chef-rbenv.git', :ref => 'v0.7.2'
cookbook 'nginx'
cookbook 'imagemagick'
